#!/usr/bin/env python3
# Python-based placefile creation of Houston Lightning Mapping Array data for python-based HDWX
# Created 21 December 2021 by Sam Gardner <stgardner4@tamu.edu>

import hlmaFetch
from os import path, listdir
from pyxlma.lmalib.io import read as lma_read
import pandas as pd
import numpy as np
from datetime import datetime as dt, timedelta
from pathlib import Path
import json
from shutil import copyfile
import warnings
basePath = path.abspath(path.dirname(__file__))
hasHelpers = False
if path.exists(path.join(basePath, "HDWX_helpers.py")):
    import HDWX_helpers
    hasHelpers = True


def makeSrcPlacefile(lmaFilePaths, elapsedTimeOfPlot):
    # Silence error_bad_lines warning when reading in LMA data
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore")
        # Read in LMA data
        lmaDataMaster, startTimeOfPlot = lma_read.dataset(lmaFilePaths)
        qc_mask = np.where((lmaDataMaster.event_chi2.data <= 1) & (lmaDataMaster.event_altitude.data <= 20000))[0]
        lmaDataMaster = lmaDataMaster.isel(number_of_events=qc_mask)
    # Get time of the plot for metadata
    lastFileName = path.basename(lmaFilePaths[-1])
    timeOfPlot = dt.strptime(lastFileName.split("_")[1]+lastFileName.split("_")[2], "%y%m%d%H%M%S")+timedelta(seconds=int(lastFileName.split("_")[3].replace(".dat", "").replace(".gz", "")))
    thisTimeStep = timeOfPlot + timedelta(seconds=int(lastFileName.split("_")[-1].replace(".dat", "").replace(".gz", "")))
    # Create a GR2Analyst compatible placefile
    if elapsedTimeOfPlot.total_seconds() <= 90:
        outFileName = "1min-src"
        placeFileString = ";One-minute WTLMA Data\n;Generated by pyxlma on python-based HDWX\n;Installation instructions: GR2Analyst -> Window -> Placefile manager -> + -> Add the URL to this file\n;Valid: "+dt.strftime(timeOfPlot, "%Y-%m-%d %H:%M")+"\n;Code by Sam Gardner <samuel.gardner@ttu.edu>\nThreshold: 999\nRefresh: 1\nIconFile: 1, 32, 32, 16, 16, http://lightning.ttu.edu/stg/gr2a/lightningicons.png\n"
        productID = 142
    else:
        outFileName = "5min-src"
        placeFileString = ";Five-minute WTLMA Data\n;Generated by pyxlma on python-based HDWX\n;Installation instructions: GR2Analyst -> Window -> Placefile manager -> + -> Add the URL to this file\n;Valid: "+dt.strftime(timeOfPlot, "%Y-%m-%d %H:%M")+"\n;Code by Sam Gardner <samuel.gardner@ttu.edu>\nThreshold: 999\nRefresh: 1\nIconFile: 1, 32, 32, 16, 16, http://lightning.ttu.edu/stg/gr2a/lightningicons.png\n"
        productID = 145
    # Add all of our lightning points, one minute at a time with appropriate TimeRange headers:
    while thisTimeStep > startTimeOfPlot:
        timeStepStart = thisTimeStep - timedelta(seconds=elapsedTimeOfPlot.total_seconds())
        print(thisTimeStep)
        point_mask = np.where((lmaDataMaster.event_time.data < np.array([thisTimeStep]).astype('datetime64[ns]')) &
                              (lmaDataMaster.event_time.data >= np.array([timeStepStart]).astype('datetime64[ns]')))[0]
        placeFileString = placeFileString+f"\nTimeRange: {timeStepStart.strftime('%Y-%m-%dT%H:%M:%SZ')} {thisTimeStep.strftime('%Y-%m-%dT%H:%M:%SZ')}\n"
        numRows = len(point_mask)
        if numRows > 0:
            lmaData = lmaDataMaster.isel(number_of_events=point_mask)
            if numRows > 1:
                scaleOfPoint = 1+((lmaData.event_time.data - lmaData.event_time.data[0]).astype(float)/float(lmaData.event_time.data[-1] - lmaData.event_time.data[0])*1024).astype(int)
            else:
                scaleOfPoint = np.array([1])
            outArr0 = np.char.add(np.full((numRows, 1), "Icon: ", dtype="|S6").astype(str), lmaData.event_latitude.data.astype(str).reshape(numRows, 1))
            outArr0 = np.char.add(outArr0, np.full((numRows, 1), ", ", dtype="|S2").astype(str))
            outArr0 = np.char.add(outArr0, lmaData.event_longitude.data.astype(str).reshape(numRows, 1))
            outArr0 = np.char.add(outArr0, np.full((numRows, 1), ", 000, 1, ", dtype="|S10").astype(str))
            outArr0 = np.char.add(outArr0, scaleOfPoint.astype(str).reshape(numRows, 1))
            outArr0 = np.char.add(outArr0, np.full((numRows, 1), ", ", dtype="|S2").astype(str))
            outArr0 = np.char.add(outArr0, np.char.replace(lmaData.event_time.data.astype(str), dt.utcnow().strftime("%Y-%m-%dT"), "").reshape(numRows, 1))
            outArr0 = np.char.add(outArr0, np.full((numRows, 1), "\\nAltitude (m):", dtype="|S16").astype(str))
            outArr0 = np.char.add(outArr0, lmaData.event_altitude.data.astype(str).reshape(numRows, 1))
            outArr0 = np.char.add(outArr0, np.full((numRows, 1), "\\nReduced chi^2:", dtype="|S17").astype(str))
            outArr0 = np.char.add(outArr0, lmaData.event_chi2.data.astype(str).reshape(numRows, 1))
            outArr0 = np.char.add(outArr0, np.full((numRows, 1), "\\nPower (dBW):", dtype="|S15").astype(str))
            outArr0 = np.char.add(outArr0, lmaData.event_power.data.astype(str).reshape(numRows, 1))
            outArr0 = np.char.add(outArr0, np.full((numRows, 1), "\\nStation Count:", dtype="|S17").astype(str))
            outArr0 = np.char.add(outArr0, lmaData.event_stations.data.astype(str).reshape(numRows, 1)).flatten()
            placeFileString = placeFileString+"\n".join(outArr0)
        thisTimeStep = timeStepStart
    # Create a path object for GR2A placefile's productPath
    gr2aProductPath = path.join("gr2a", "")
    # Target path for gr2a placefiles is output/gr2a/1min-src.txt
    gr2aSavePath = path.join(basePath, "output", gr2aProductPath, outFileName+".txt")
    # Create parent dir
    Path(path.dirname(gr2aSavePath)).mkdir(parents=True, exist_ok=True)
    # write out the placefile
    with open(gr2aSavePath, "w") as textWrite:
        textWrite.write(placeFileString)
    # Also write out php file for the website (this is necessary because pointing browser at a txt will result in caching)
    phpText = "<?php\n    header('Content-type: text/plain');\n    echo file_get_contents(\"./"+outFileName+".txt\")\n?>"
    with open(path.join(basePath, "output", gr2aProductPath, outFileName+".php"), "w") as phpWrite:
        phpWrite.write(phpText)
    if not path.exists(path.join(basePath, "output", gr2aProductPath, "lightningicons.png")):
        if path.exists(path.join(basePath, "assets", "icons.png")):
            copyfile(path.join(basePath, "assets", "icons.png"), path.join(basePath, "output", gr2aProductPath, "lightningicons.png"))
    # write metadata for gr2a file
    if hasHelpers:
        HDWX_helpers.writeJson(basePath, productID, timeOfPlot, outFileName+".txt", timeOfPlot, ["0,0", "0,0"], 60)

if __name__ == "__main__":
    # get path to starting dir
    basePath = path.dirname(path.abspath(__file__))
    # get path to input files
    inputPath = path.join(basePath, "lightningin")
    # List the files in the input directory
    filesToPlot = sorted(listdir(inputPath))
    # If there are no files in the input dir, exit immediately
    if len(filesToPlot) == 0:
        exit()
    # Get the time of the latest data
    for file in reversed(filesToPlot):
        lastMinFileDt = dt.strptime(file.split("_")[1]+file.split("_")[2], "%y%m%d%H%M%S")
        elapsedTime = int(file.split("_")[-1].replace(".dat", "").replace(".gz", ""))
        elapsedTime = timedelta(seconds=elapsedTime)
        lastMinFileDtEnd = lastMinFileDt + elapsedTime
        if lastMinFileDtEnd.second == 0:
            break
    # Get paths to most recent hour
    startTimeForPeriod = lastMinFileDt - timedelta(minutes=20) + elapsedTime
    lastHourFiles = hlmaFetch.getLmaFilesBetweenTimes(startTimeForPeriod, lastMinFileDt, True)
    # Check to see if the one-minute placefile has the latest input file generated
    # Read in metadata for one minute placefile
    oneMinMetadataPath = path.join(basePath, "output", "metadata", "products", "142", lastMinFileDt.strftime("%Y%m%d%H00")+".json")
    if path.exists(oneMinMetadataPath):
        with open(oneMinMetadataPath, "r") as jsonRead:
            lastOneMinMetadata = json.load(jsonRead)
        # If the latest lma input file is newer than the last generated placefile, generate a new one
        if int(lastOneMinMetadata["productFrames"][0]["valid"]) < int(lastMinFileDt.strftime("%Y%m%d%H%M")):
            makeSrcPlacefile(lastHourFiles, timedelta(seconds=60))
    else:
        # If the json doesn't exist, then we definitely need to plot the latest file.
        makeSrcPlacefile(lastHourFiles, timedelta(seconds=60))
    # Now let's make a placefile accumulating five minutes of data
    fiveMinMetadataPath = path.join(basePath, "output", "metadata", "products", "145", lastMinFileDt.strftime("%Y%m%d%H00")+".json")
    if path.exists(fiveMinMetadataPath):
        with open(fiveMinMetadataPath, "r") as jsonRead:
            lastFiveMinMetadata = json.load(jsonRead)
        if int(lastFiveMinMetadata["productFrames"][0]["valid"]) < int(lastMinFileDt.strftime("%Y%m%d%H%M")):
            makeSrcPlacefile(lastHourFiles, timedelta(seconds=300))
    else:
        makeSrcPlacefile(lastHourFiles, timedelta(seconds=300))
